# Generated by Django 5.1.2 on 2024-10-16 00:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfWork_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 10, 16, 0, 13, 25, 995807, tzinfo=datetime.timezone.utc))),
                ('work_text', models.TextField(default='')),
                ('manhour', models.FloatField(default=0)),
                ('typeOfWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.typeofwork')),
            ],
        ),
    ]
